#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medismart_Tools
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RSUD_TERNATE")]
	public partial class DCMedismartToolsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPASIEN(PASIEN instance);
    partial void UpdatePASIEN(PASIEN instance);
    partial void DeletePASIEN(PASIEN instance);
    partial void InsertUNIT(UNIT instance);
    partial void UpdateUNIT(UNIT instance);
    partial void DeleteUNIT(UNIT instance);
    partial void InsertDOKTER(DOKTER instance);
    partial void UpdateDOKTER(DOKTER instance);
    partial void DeleteDOKTER(DOKTER instance);
    partial void InsertCUSTOMER(CUSTOMER instance);
    partial void UpdateCUSTOMER(CUSTOMER instance);
    partial void DeleteCUSTOMER(CUSTOMER instance);
    partial void InsertKUNJUNGAN(KUNJUNGAN instance);
    partial void UpdateKUNJUNGAN(KUNJUNGAN instance);
    partial void DeleteKUNJUNGAN(KUNJUNGAN instance);
    partial void InsertKAMAR_INDUK(KAMAR_INDUK instance);
    partial void UpdateKAMAR_INDUK(KAMAR_INDUK instance);
    partial void DeleteKAMAR_INDUK(KAMAR_INDUK instance);
    partial void InsertNGINAP(NGINAP instance);
    partial void UpdateNGINAP(NGINAP instance);
    partial void DeleteNGINAP(NGINAP instance);
    partial void InsertPASIEN_INAP(PASIEN_INAP instance);
    partial void UpdatePASIEN_INAP(PASIEN_INAP instance);
    partial void DeletePASIEN_INAP(PASIEN_INAP instance);
    partial void InsertTRANSAKSI(TRANSAKSI instance);
    partial void UpdateTRANSAKSI(TRANSAKSI instance);
    partial void DeleteTRANSAKSI(TRANSAKSI instance);
    partial void InsertPAYMENT(PAYMENT instance);
    partial void UpdatePAYMENT(PAYMENT instance);
    partial void DeletePAYMENT(PAYMENT instance);
    #endregion
		
		public DCMedismartToolsDataContext() : 
				base(global::Medismart_Tools.Properties.Settings.Default.RSUD_TERNATEConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DCMedismartToolsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCMedismartToolsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCMedismartToolsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCMedismartToolsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PASIEN> PASIENs
		{
			get
			{
				return this.GetTable<PASIEN>();
			}
		}
		
		public System.Data.Linq.Table<UNIT> UNITs
		{
			get
			{
				return this.GetTable<UNIT>();
			}
		}
		
		public System.Data.Linq.Table<DOKTER> DOKTERs
		{
			get
			{
				return this.GetTable<DOKTER>();
			}
		}
		
		public System.Data.Linq.Table<CUSTOMER> CUSTOMERs
		{
			get
			{
				return this.GetTable<CUSTOMER>();
			}
		}
		
		public System.Data.Linq.Table<KUNJUNGAN> KUNJUNGANs
		{
			get
			{
				return this.GetTable<KUNJUNGAN>();
			}
		}
		
		public System.Data.Linq.Table<KAMAR_INDUK> KAMAR_INDUKs
		{
			get
			{
				return this.GetTable<KAMAR_INDUK>();
			}
		}
		
		public System.Data.Linq.Table<NGINAP> NGINAPs
		{
			get
			{
				return this.GetTable<NGINAP>();
			}
		}
		
		public System.Data.Linq.Table<PASIEN_INAP> PASIEN_INAPs
		{
			get
			{
				return this.GetTable<PASIEN_INAP>();
			}
		}
		
		public System.Data.Linq.Table<TRANSAKSI> TRANSAKSIs
		{
			get
			{
				return this.GetTable<TRANSAKSI>();
			}
		}
		
		public System.Data.Linq.Table<PAYMENT> PAYMENTs
		{
			get
			{
				return this.GetTable<PAYMENT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PASIEN")]
	public partial class PASIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _KD_PASIEN;
		
		private System.Nullable<int> _KD_KELURAHAN;
		
		private System.Nullable<byte> _KD_PENDIDIKAN;
		
		private System.Nullable<byte> _KD_PEKERJAAN;
		
		private System.Nullable<int> _KD_PERUSAHAAN;
		
		private System.Nullable<byte> _KD_AGAMA;
		
		private string _NAMA;
		
		private System.Nullable<System.DateTime> _TGL_LAHIR;
		
		private string _GOL_DARAH;
		
		private System.Nullable<bool> _JENIS_KELAMIN;
		
		private System.Nullable<bool> _STATUS_HIDUP;
		
		private System.Nullable<byte> _STATUS_MARITA;
		
		private string _ALAMAT;
		
		private string _KOTA;
		
		private string _TELEPON;
		
		private string _KD_POS;
		
		private System.Nullable<byte> _KD_ASURANSI;
		
		private string _NO_ASURANSI;
		
		private string _JABATAN;
		
		private System.Nullable<byte> _TANDA_PENGENAL;
		
		private string _NO_PENGENAL;
		
		private string _KETERANGAN;
		
		private string _KODE_LAMA;
		
		private bool _WNI;
		
		private string _NAMA_KELUARGA;
		
		private string _TEMPAT_LAHIR;
		
		private string _PEMEGANG_ASURANSI;
		
		private string _NO_REG_LAMA;
		
		private int _KD_SUKU;
		
		private System.Nullable<int> _KET_SIMPAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKD_PASIENChanging(string value);
    partial void OnKD_PASIENChanged();
    partial void OnKD_KELURAHANChanging(System.Nullable<int> value);
    partial void OnKD_KELURAHANChanged();
    partial void OnKD_PENDIDIKANChanging(System.Nullable<byte> value);
    partial void OnKD_PENDIDIKANChanged();
    partial void OnKD_PEKERJAANChanging(System.Nullable<byte> value);
    partial void OnKD_PEKERJAANChanged();
    partial void OnKD_PERUSAHAANChanging(System.Nullable<int> value);
    partial void OnKD_PERUSAHAANChanged();
    partial void OnKD_AGAMAChanging(System.Nullable<byte> value);
    partial void OnKD_AGAMAChanged();
    partial void OnNAMAChanging(string value);
    partial void OnNAMAChanged();
    partial void OnTGL_LAHIRChanging(System.Nullable<System.DateTime> value);
    partial void OnTGL_LAHIRChanged();
    partial void OnGOL_DARAHChanging(string value);
    partial void OnGOL_DARAHChanged();
    partial void OnJENIS_KELAMINChanging(System.Nullable<bool> value);
    partial void OnJENIS_KELAMINChanged();
    partial void OnSTATUS_HIDUPChanging(System.Nullable<bool> value);
    partial void OnSTATUS_HIDUPChanged();
    partial void OnSTATUS_MARITAChanging(System.Nullable<byte> value);
    partial void OnSTATUS_MARITAChanged();
    partial void OnALAMATChanging(string value);
    partial void OnALAMATChanged();
    partial void OnKOTAChanging(string value);
    partial void OnKOTAChanged();
    partial void OnTELEPONChanging(string value);
    partial void OnTELEPONChanged();
    partial void OnKD_POSChanging(string value);
    partial void OnKD_POSChanged();
    partial void OnKD_ASURANSIChanging(System.Nullable<byte> value);
    partial void OnKD_ASURANSIChanged();
    partial void OnNO_ASURANSIChanging(string value);
    partial void OnNO_ASURANSIChanged();
    partial void OnJABATANChanging(string value);
    partial void OnJABATANChanged();
    partial void OnTANDA_PENGENALChanging(System.Nullable<byte> value);
    partial void OnTANDA_PENGENALChanged();
    partial void OnNO_PENGENALChanging(string value);
    partial void OnNO_PENGENALChanged();
    partial void OnKETERANGANChanging(string value);
    partial void OnKETERANGANChanged();
    partial void OnKODE_LAMAChanging(string value);
    partial void OnKODE_LAMAChanged();
    partial void OnWNIChanging(bool value);
    partial void OnWNIChanged();
    partial void OnNAMA_KELUARGAChanging(string value);
    partial void OnNAMA_KELUARGAChanged();
    partial void OnTEMPAT_LAHIRChanging(string value);
    partial void OnTEMPAT_LAHIRChanged();
    partial void OnPEMEGANG_ASURANSIChanging(string value);
    partial void OnPEMEGANG_ASURANSIChanged();
    partial void OnNO_REG_LAMAChanging(string value);
    partial void OnNO_REG_LAMAChanged();
    partial void OnKD_SUKUChanging(int value);
    partial void OnKD_SUKUChanged();
    partial void OnKET_SIMPANChanging(System.Nullable<int> value);
    partial void OnKET_SIMPANChanged();
    #endregion
		
		public PASIEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_PASIEN", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string KD_PASIEN
		{
			get
			{
				return this._KD_PASIEN;
			}
			set
			{
				if ((this._KD_PASIEN != value))
				{
					this.OnKD_PASIENChanging(value);
					this.SendPropertyChanging();
					this._KD_PASIEN = value;
					this.SendPropertyChanged("KD_PASIEN");
					this.OnKD_PASIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_KELURAHAN", DbType="Int")]
		public System.Nullable<int> KD_KELURAHAN
		{
			get
			{
				return this._KD_KELURAHAN;
			}
			set
			{
				if ((this._KD_KELURAHAN != value))
				{
					this.OnKD_KELURAHANChanging(value);
					this.SendPropertyChanging();
					this._KD_KELURAHAN = value;
					this.SendPropertyChanged("KD_KELURAHAN");
					this.OnKD_KELURAHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_PENDIDIKAN", DbType="TinyInt")]
		public System.Nullable<byte> KD_PENDIDIKAN
		{
			get
			{
				return this._KD_PENDIDIKAN;
			}
			set
			{
				if ((this._KD_PENDIDIKAN != value))
				{
					this.OnKD_PENDIDIKANChanging(value);
					this.SendPropertyChanging();
					this._KD_PENDIDIKAN = value;
					this.SendPropertyChanged("KD_PENDIDIKAN");
					this.OnKD_PENDIDIKANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_PEKERJAAN", DbType="TinyInt")]
		public System.Nullable<byte> KD_PEKERJAAN
		{
			get
			{
				return this._KD_PEKERJAAN;
			}
			set
			{
				if ((this._KD_PEKERJAAN != value))
				{
					this.OnKD_PEKERJAANChanging(value);
					this.SendPropertyChanging();
					this._KD_PEKERJAAN = value;
					this.SendPropertyChanged("KD_PEKERJAAN");
					this.OnKD_PEKERJAANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_PERUSAHAAN", DbType="Int")]
		public System.Nullable<int> KD_PERUSAHAAN
		{
			get
			{
				return this._KD_PERUSAHAAN;
			}
			set
			{
				if ((this._KD_PERUSAHAAN != value))
				{
					this.OnKD_PERUSAHAANChanging(value);
					this.SendPropertyChanging();
					this._KD_PERUSAHAAN = value;
					this.SendPropertyChanged("KD_PERUSAHAAN");
					this.OnKD_PERUSAHAANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_AGAMA", DbType="TinyInt")]
		public System.Nullable<byte> KD_AGAMA
		{
			get
			{
				return this._KD_AGAMA;
			}
			set
			{
				if ((this._KD_AGAMA != value))
				{
					this.OnKD_AGAMAChanging(value);
					this.SendPropertyChanging();
					this._KD_AGAMA = value;
					this.SendPropertyChanged("KD_AGAMA");
					this.OnKD_AGAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(50)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this.OnNAMAChanging(value);
					this.SendPropertyChanging();
					this._NAMA = value;
					this.SendPropertyChanged("NAMA");
					this.OnNAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGL_LAHIR", DbType="DateTime")]
		public System.Nullable<System.DateTime> TGL_LAHIR
		{
			get
			{
				return this._TGL_LAHIR;
			}
			set
			{
				if ((this._TGL_LAHIR != value))
				{
					this.OnTGL_LAHIRChanging(value);
					this.SendPropertyChanging();
					this._TGL_LAHIR = value;
					this.SendPropertyChanged("TGL_LAHIR");
					this.OnTGL_LAHIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOL_DARAH", DbType="VarChar(2)")]
		public string GOL_DARAH
		{
			get
			{
				return this._GOL_DARAH;
			}
			set
			{
				if ((this._GOL_DARAH != value))
				{
					this.OnGOL_DARAHChanging(value);
					this.SendPropertyChanging();
					this._GOL_DARAH = value;
					this.SendPropertyChanged("GOL_DARAH");
					this.OnGOL_DARAHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JENIS_KELAMIN", DbType="Bit")]
		public System.Nullable<bool> JENIS_KELAMIN
		{
			get
			{
				return this._JENIS_KELAMIN;
			}
			set
			{
				if ((this._JENIS_KELAMIN != value))
				{
					this.OnJENIS_KELAMINChanging(value);
					this.SendPropertyChanging();
					this._JENIS_KELAMIN = value;
					this.SendPropertyChanged("JENIS_KELAMIN");
					this.OnJENIS_KELAMINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_HIDUP", DbType="Bit")]
		public System.Nullable<bool> STATUS_HIDUP
		{
			get
			{
				return this._STATUS_HIDUP;
			}
			set
			{
				if ((this._STATUS_HIDUP != value))
				{
					this.OnSTATUS_HIDUPChanging(value);
					this.SendPropertyChanging();
					this._STATUS_HIDUP = value;
					this.SendPropertyChanged("STATUS_HIDUP");
					this.OnSTATUS_HIDUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_MARITA", DbType="TinyInt")]
		public System.Nullable<byte> STATUS_MARITA
		{
			get
			{
				return this._STATUS_MARITA;
			}
			set
			{
				if ((this._STATUS_MARITA != value))
				{
					this.OnSTATUS_MARITAChanging(value);
					this.SendPropertyChanging();
					this._STATUS_MARITA = value;
					this.SendPropertyChanged("STATUS_MARITA");
					this.OnSTATUS_MARITAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALAMAT", DbType="VarChar(90)")]
		public string ALAMAT
		{
			get
			{
				return this._ALAMAT;
			}
			set
			{
				if ((this._ALAMAT != value))
				{
					this.OnALAMATChanging(value);
					this.SendPropertyChanging();
					this._ALAMAT = value;
					this.SendPropertyChanged("ALAMAT");
					this.OnALAMATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOTA", DbType="VarChar(30)")]
		public string KOTA
		{
			get
			{
				return this._KOTA;
			}
			set
			{
				if ((this._KOTA != value))
				{
					this.OnKOTAChanging(value);
					this.SendPropertyChanging();
					this._KOTA = value;
					this.SendPropertyChanged("KOTA");
					this.OnKOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEPON", DbType="VarChar(40)")]
		public string TELEPON
		{
			get
			{
				return this._TELEPON;
			}
			set
			{
				if ((this._TELEPON != value))
				{
					this.OnTELEPONChanging(value);
					this.SendPropertyChanging();
					this._TELEPON = value;
					this.SendPropertyChanged("TELEPON");
					this.OnTELEPONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_POS", DbType="VarChar(5)")]
		public string KD_POS
		{
			get
			{
				return this._KD_POS;
			}
			set
			{
				if ((this._KD_POS != value))
				{
					this.OnKD_POSChanging(value);
					this.SendPropertyChanging();
					this._KD_POS = value;
					this.SendPropertyChanged("KD_POS");
					this.OnKD_POSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_ASURANSI", DbType="TinyInt")]
		public System.Nullable<byte> KD_ASURANSI
		{
			get
			{
				return this._KD_ASURANSI;
			}
			set
			{
				if ((this._KD_ASURANSI != value))
				{
					this.OnKD_ASURANSIChanging(value);
					this.SendPropertyChanging();
					this._KD_ASURANSI = value;
					this.SendPropertyChanged("KD_ASURANSI");
					this.OnKD_ASURANSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_ASURANSI", DbType="VarChar(20)")]
		public string NO_ASURANSI
		{
			get
			{
				return this._NO_ASURANSI;
			}
			set
			{
				if ((this._NO_ASURANSI != value))
				{
					this.OnNO_ASURANSIChanging(value);
					this.SendPropertyChanging();
					this._NO_ASURANSI = value;
					this.SendPropertyChanged("NO_ASURANSI");
					this.OnNO_ASURANSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JABATAN", DbType="Char(20)")]
		public string JABATAN
		{
			get
			{
				return this._JABATAN;
			}
			set
			{
				if ((this._JABATAN != value))
				{
					this.OnJABATANChanging(value);
					this.SendPropertyChanging();
					this._JABATAN = value;
					this.SendPropertyChanged("JABATAN");
					this.OnJABATANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TANDA_PENGENAL", DbType="TinyInt")]
		public System.Nullable<byte> TANDA_PENGENAL
		{
			get
			{
				return this._TANDA_PENGENAL;
			}
			set
			{
				if ((this._TANDA_PENGENAL != value))
				{
					this.OnTANDA_PENGENALChanging(value);
					this.SendPropertyChanging();
					this._TANDA_PENGENAL = value;
					this.SendPropertyChanged("TANDA_PENGENAL");
					this.OnTANDA_PENGENALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_PENGENAL", DbType="VarChar(50)")]
		public string NO_PENGENAL
		{
			get
			{
				return this._NO_PENGENAL;
			}
			set
			{
				if ((this._NO_PENGENAL != value))
				{
					this.OnNO_PENGENALChanging(value);
					this.SendPropertyChanging();
					this._NO_PENGENAL = value;
					this.SendPropertyChanged("NO_PENGENAL");
					this.OnNO_PENGENALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KETERANGAN", DbType="VarChar(1024)")]
		public string KETERANGAN
		{
			get
			{
				return this._KETERANGAN;
			}
			set
			{
				if ((this._KETERANGAN != value))
				{
					this.OnKETERANGANChanging(value);
					this.SendPropertyChanging();
					this._KETERANGAN = value;
					this.SendPropertyChanged("KETERANGAN");
					this.OnKETERANGANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KODE_LAMA", DbType="VarChar(12)")]
		public string KODE_LAMA
		{
			get
			{
				return this._KODE_LAMA;
			}
			set
			{
				if ((this._KODE_LAMA != value))
				{
					this.OnKODE_LAMAChanging(value);
					this.SendPropertyChanging();
					this._KODE_LAMA = value;
					this.SendPropertyChanged("KODE_LAMA");
					this.OnKODE_LAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WNI", DbType="Bit NOT NULL")]
		public bool WNI
		{
			get
			{
				return this._WNI;
			}
			set
			{
				if ((this._WNI != value))
				{
					this.OnWNIChanging(value);
					this.SendPropertyChanging();
					this._WNI = value;
					this.SendPropertyChanged("WNI");
					this.OnWNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_KELUARGA", DbType="VarChar(50)")]
		public string NAMA_KELUARGA
		{
			get
			{
				return this._NAMA_KELUARGA;
			}
			set
			{
				if ((this._NAMA_KELUARGA != value))
				{
					this.OnNAMA_KELUARGAChanging(value);
					this.SendPropertyChanging();
					this._NAMA_KELUARGA = value;
					this.SendPropertyChanged("NAMA_KELUARGA");
					this.OnNAMA_KELUARGAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEMPAT_LAHIR", DbType="VarChar(25)")]
		public string TEMPAT_LAHIR
		{
			get
			{
				return this._TEMPAT_LAHIR;
			}
			set
			{
				if ((this._TEMPAT_LAHIR != value))
				{
					this.OnTEMPAT_LAHIRChanging(value);
					this.SendPropertyChanging();
					this._TEMPAT_LAHIR = value;
					this.SendPropertyChanged("TEMPAT_LAHIR");
					this.OnTEMPAT_LAHIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PEMEGANG_ASURANSI", DbType="VarChar(50)")]
		public string PEMEGANG_ASURANSI
		{
			get
			{
				return this._PEMEGANG_ASURANSI;
			}
			set
			{
				if ((this._PEMEGANG_ASURANSI != value))
				{
					this.OnPEMEGANG_ASURANSIChanging(value);
					this.SendPropertyChanging();
					this._PEMEGANG_ASURANSI = value;
					this.SendPropertyChanged("PEMEGANG_ASURANSI");
					this.OnPEMEGANG_ASURANSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_REG_LAMA", DbType="VarChar(15)")]
		public string NO_REG_LAMA
		{
			get
			{
				return this._NO_REG_LAMA;
			}
			set
			{
				if ((this._NO_REG_LAMA != value))
				{
					this.OnNO_REG_LAMAChanging(value);
					this.SendPropertyChanging();
					this._NO_REG_LAMA = value;
					this.SendPropertyChanged("NO_REG_LAMA");
					this.OnNO_REG_LAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_SUKU", DbType="Int NOT NULL")]
		public int KD_SUKU
		{
			get
			{
				return this._KD_SUKU;
			}
			set
			{
				if ((this._KD_SUKU != value))
				{
					this.OnKD_SUKUChanging(value);
					this.SendPropertyChanging();
					this._KD_SUKU = value;
					this.SendPropertyChanged("KD_SUKU");
					this.OnKD_SUKUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KET_SIMPAN", DbType="Int")]
		public System.Nullable<int> KET_SIMPAN
		{
			get
			{
				return this._KET_SIMPAN;
			}
			set
			{
				if ((this._KET_SIMPAN != value))
				{
					this.OnKET_SIMPANChanging(value);
					this.SendPropertyChanging();
					this._KET_SIMPAN = value;
					this.SendPropertyChanged("KET_SIMPAN");
					this.OnKET_SIMPANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UNIT")]
	public partial class UNIT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _KD_UNIT;
		
		private byte _KD_BAGIAN;
		
		private byte _KD_KELAS;
		
		private string _NAMA_UNIT;
		
		private string _PARENT;
		
		private bool _TYPE;
		
		private bool _AKTIF;
		
		private bool _SPESIAL;
		
		private string _UNIT_GROUP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKD_UNITChanging(string value);
    partial void OnKD_UNITChanged();
    partial void OnKD_BAGIANChanging(byte value);
    partial void OnKD_BAGIANChanged();
    partial void OnKD_KELASChanging(byte value);
    partial void OnKD_KELASChanged();
    partial void OnNAMA_UNITChanging(string value);
    partial void OnNAMA_UNITChanged();
    partial void OnPARENTChanging(string value);
    partial void OnPARENTChanged();
    partial void OnTYPEChanging(bool value);
    partial void OnTYPEChanged();
    partial void OnAKTIFChanging(bool value);
    partial void OnAKTIFChanged();
    partial void OnSPESIALChanging(bool value);
    partial void OnSPESIALChanged();
    partial void OnUNIT_GROUPChanging(string value);
    partial void OnUNIT_GROUPChanged();
    #endregion
		
		public UNIT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_UNIT", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string KD_UNIT
		{
			get
			{
				return this._KD_UNIT;
			}
			set
			{
				if ((this._KD_UNIT != value))
				{
					this.OnKD_UNITChanging(value);
					this.SendPropertyChanging();
					this._KD_UNIT = value;
					this.SendPropertyChanged("KD_UNIT");
					this.OnKD_UNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_BAGIAN", DbType="TinyInt NOT NULL")]
		public byte KD_BAGIAN
		{
			get
			{
				return this._KD_BAGIAN;
			}
			set
			{
				if ((this._KD_BAGIAN != value))
				{
					this.OnKD_BAGIANChanging(value);
					this.SendPropertyChanging();
					this._KD_BAGIAN = value;
					this.SendPropertyChanged("KD_BAGIAN");
					this.OnKD_BAGIANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_KELAS", DbType="TinyInt NOT NULL")]
		public byte KD_KELAS
		{
			get
			{
				return this._KD_KELAS;
			}
			set
			{
				if ((this._KD_KELAS != value))
				{
					this.OnKD_KELASChanging(value);
					this.SendPropertyChanging();
					this._KD_KELAS = value;
					this.SendPropertyChanged("KD_KELAS");
					this.OnKD_KELASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_UNIT", DbType="VarChar(25)")]
		public string NAMA_UNIT
		{
			get
			{
				return this._NAMA_UNIT;
			}
			set
			{
				if ((this._NAMA_UNIT != value))
				{
					this.OnNAMA_UNITChanging(value);
					this.SendPropertyChanging();
					this._NAMA_UNIT = value;
					this.SendPropertyChanged("NAMA_UNIT");
					this.OnNAMA_UNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT", DbType="VarChar(5)")]
		public string PARENT
		{
			get
			{
				return this._PARENT;
			}
			set
			{
				if ((this._PARENT != value))
				{
					this.OnPARENTChanging(value);
					this.SendPropertyChanging();
					this._PARENT = value;
					this.SendPropertyChanged("PARENT");
					this.OnPARENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="Bit NOT NULL")]
		public bool TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKTIF", DbType="Bit NOT NULL")]
		public bool AKTIF
		{
			get
			{
				return this._AKTIF;
			}
			set
			{
				if ((this._AKTIF != value))
				{
					this.OnAKTIFChanging(value);
					this.SendPropertyChanging();
					this._AKTIF = value;
					this.SendPropertyChanged("AKTIF");
					this.OnAKTIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPESIAL", DbType="Bit NOT NULL")]
		public bool SPESIAL
		{
			get
			{
				return this._SPESIAL;
			}
			set
			{
				if ((this._SPESIAL != value))
				{
					this.OnSPESIALChanging(value);
					this.SendPropertyChanging();
					this._SPESIAL = value;
					this.SendPropertyChanged("SPESIAL");
					this.OnSPESIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_GROUP", DbType="VarChar(25)")]
		public string UNIT_GROUP
		{
			get
			{
				return this._UNIT_GROUP;
			}
			set
			{
				if ((this._UNIT_GROUP != value))
				{
					this.OnUNIT_GROUPChanging(value);
					this.SendPropertyChanging();
					this._UNIT_GROUP = value;
					this.SendPropertyChanged("UNIT_GROUP");
					this.OnUNIT_GROUPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOKTER")]
	public partial class DOKTER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _KD_DOKTER;
		
		private string _NAMA;
		
		private string _NIP;
		
		private string _JABATAN;
		
		private int _STATUS;
		
		private string _PASSWORD;
		
		private byte _JENIS_DOKTER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKD_DOKTERChanging(string value);
    partial void OnKD_DOKTERChanged();
    partial void OnNAMAChanging(string value);
    partial void OnNAMAChanged();
    partial void OnNIPChanging(string value);
    partial void OnNIPChanged();
    partial void OnJABATANChanging(string value);
    partial void OnJABATANChanged();
    partial void OnSTATUSChanging(int value);
    partial void OnSTATUSChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnJENIS_DOKTERChanging(byte value);
    partial void OnJENIS_DOKTERChanged();
    #endregion
		
		public DOKTER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_DOKTER", DbType="VarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string KD_DOKTER
		{
			get
			{
				return this._KD_DOKTER;
			}
			set
			{
				if ((this._KD_DOKTER != value))
				{
					this.OnKD_DOKTERChanging(value);
					this.SendPropertyChanging();
					this._KD_DOKTER = value;
					this.SendPropertyChanged("KD_DOKTER");
					this.OnKD_DOKTERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(50)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this.OnNAMAChanging(value);
					this.SendPropertyChanging();
					this._NAMA = value;
					this.SendPropertyChanged("NAMA");
					this.OnNAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIP", DbType="VarChar(9)")]
		public string NIP
		{
			get
			{
				return this._NIP;
			}
			set
			{
				if ((this._NIP != value))
				{
					this.OnNIPChanging(value);
					this.SendPropertyChanging();
					this._NIP = value;
					this.SendPropertyChanged("NIP");
					this.OnNIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JABATAN", DbType="Char(20)")]
		public string JABATAN
		{
			get
			{
				return this._JABATAN;
			}
			set
			{
				if ((this._JABATAN != value))
				{
					this.OnJABATANChanging(value);
					this.SendPropertyChanging();
					this._JABATAN = value;
					this.SendPropertyChanged("JABATAN");
					this.OnJABATANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int NOT NULL")]
		public int STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JENIS_DOKTER", DbType="TinyInt NOT NULL")]
		public byte JENIS_DOKTER
		{
			get
			{
				return this._JENIS_DOKTER;
			}
			set
			{
				if ((this._JENIS_DOKTER != value))
				{
					this.OnJENIS_DOKTERChanging(value);
					this.SendPropertyChanging();
					this._JENIS_DOKTER = value;
					this.SendPropertyChanged("JENIS_DOKTER");
					this.OnJENIS_DOKTERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUSTOMER")]
	public partial class CUSTOMER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _KD_CUSTOMER;
		
		private string _ACCOUNT;
		
		private string _CUSTOMER1;
		
		private string _CONTACT;
		
		private string _ALAMAT;
		
		private string _KOTA;
		
		private string _TELEPON1;
		
		private string _TELEPON2;
		
		private string _FAX;
		
		private string _KD_POS;
		
		private string _NEGARA;
		
		private double _BEG_BAL;
		
		private System.Nullable<double> _CURRENTS;
		
		private System.Nullable<decimal> _CR_LIMIT;
		
		private System.Nullable<decimal> _FINANCE;
		
		private System.Nullable<int> _TERM;
		
		private bool _STATUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKD_CUSTOMERChanging(string value);
    partial void OnKD_CUSTOMERChanged();
    partial void OnACCOUNTChanging(string value);
    partial void OnACCOUNTChanged();
    partial void OnCUSTOMER1Changing(string value);
    partial void OnCUSTOMER1Changed();
    partial void OnCONTACTChanging(string value);
    partial void OnCONTACTChanged();
    partial void OnALAMATChanging(string value);
    partial void OnALAMATChanged();
    partial void OnKOTAChanging(string value);
    partial void OnKOTAChanged();
    partial void OnTELEPON1Changing(string value);
    partial void OnTELEPON1Changed();
    partial void OnTELEPON2Changing(string value);
    partial void OnTELEPON2Changed();
    partial void OnFAXChanging(string value);
    partial void OnFAXChanged();
    partial void OnKD_POSChanging(string value);
    partial void OnKD_POSChanged();
    partial void OnNEGARAChanging(string value);
    partial void OnNEGARAChanged();
    partial void OnBEG_BALChanging(double value);
    partial void OnBEG_BALChanged();
    partial void OnCURRENTSChanging(System.Nullable<double> value);
    partial void OnCURRENTSChanged();
    partial void OnCR_LIMITChanging(System.Nullable<decimal> value);
    partial void OnCR_LIMITChanged();
    partial void OnFINANCEChanging(System.Nullable<decimal> value);
    partial void OnFINANCEChanged();
    partial void OnTERMChanging(System.Nullable<int> value);
    partial void OnTERMChanged();
    partial void OnSTATUSChanging(bool value);
    partial void OnSTATUSChanged();
    #endregion
		
		public CUSTOMER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_CUSTOMER", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string KD_CUSTOMER
		{
			get
			{
				return this._KD_CUSTOMER;
			}
			set
			{
				if ((this._KD_CUSTOMER != value))
				{
					this.OnKD_CUSTOMERChanging(value);
					this.SendPropertyChanging();
					this._KD_CUSTOMER = value;
					this.SendPropertyChanged("KD_CUSTOMER");
					this.OnKD_CUSTOMERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT", DbType="VarChar(15)")]
		public string ACCOUNT
		{
			get
			{
				return this._ACCOUNT;
			}
			set
			{
				if ((this._ACCOUNT != value))
				{
					this.OnACCOUNTChanging(value);
					this.SendPropertyChanging();
					this._ACCOUNT = value;
					this.SendPropertyChanged("ACCOUNT");
					this.OnACCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CUSTOMER", Storage="_CUSTOMER1", DbType="VarChar(40)")]
		public string CUSTOMER1
		{
			get
			{
				return this._CUSTOMER1;
			}
			set
			{
				if ((this._CUSTOMER1 != value))
				{
					this.OnCUSTOMER1Changing(value);
					this.SendPropertyChanging();
					this._CUSTOMER1 = value;
					this.SendPropertyChanged("CUSTOMER1");
					this.OnCUSTOMER1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT", DbType="VarChar(30)")]
		public string CONTACT
		{
			get
			{
				return this._CONTACT;
			}
			set
			{
				if ((this._CONTACT != value))
				{
					this.OnCONTACTChanging(value);
					this.SendPropertyChanging();
					this._CONTACT = value;
					this.SendPropertyChanged("CONTACT");
					this.OnCONTACTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALAMAT", DbType="VarChar(50)")]
		public string ALAMAT
		{
			get
			{
				return this._ALAMAT;
			}
			set
			{
				if ((this._ALAMAT != value))
				{
					this.OnALAMATChanging(value);
					this.SendPropertyChanging();
					this._ALAMAT = value;
					this.SendPropertyChanged("ALAMAT");
					this.OnALAMATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOTA", DbType="VarChar(15)")]
		public string KOTA
		{
			get
			{
				return this._KOTA;
			}
			set
			{
				if ((this._KOTA != value))
				{
					this.OnKOTAChanging(value);
					this.SendPropertyChanging();
					this._KOTA = value;
					this.SendPropertyChanged("KOTA");
					this.OnKOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEPON1", DbType="VarChar(15)")]
		public string TELEPON1
		{
			get
			{
				return this._TELEPON1;
			}
			set
			{
				if ((this._TELEPON1 != value))
				{
					this.OnTELEPON1Changing(value);
					this.SendPropertyChanging();
					this._TELEPON1 = value;
					this.SendPropertyChanged("TELEPON1");
					this.OnTELEPON1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEPON2", DbType="VarChar(15)")]
		public string TELEPON2
		{
			get
			{
				return this._TELEPON2;
			}
			set
			{
				if ((this._TELEPON2 != value))
				{
					this.OnTELEPON2Changing(value);
					this.SendPropertyChanging();
					this._TELEPON2 = value;
					this.SendPropertyChanged("TELEPON2");
					this.OnTELEPON2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX", DbType="VarChar(15)")]
		public string FAX
		{
			get
			{
				return this._FAX;
			}
			set
			{
				if ((this._FAX != value))
				{
					this.OnFAXChanging(value);
					this.SendPropertyChanging();
					this._FAX = value;
					this.SendPropertyChanged("FAX");
					this.OnFAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_POS", DbType="VarChar(5)")]
		public string KD_POS
		{
			get
			{
				return this._KD_POS;
			}
			set
			{
				if ((this._KD_POS != value))
				{
					this.OnKD_POSChanging(value);
					this.SendPropertyChanging();
					this._KD_POS = value;
					this.SendPropertyChanged("KD_POS");
					this.OnKD_POSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NEGARA", DbType="VarChar(20)")]
		public string NEGARA
		{
			get
			{
				return this._NEGARA;
			}
			set
			{
				if ((this._NEGARA != value))
				{
					this.OnNEGARAChanging(value);
					this.SendPropertyChanging();
					this._NEGARA = value;
					this.SendPropertyChanged("NEGARA");
					this.OnNEGARAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEG_BAL", DbType="Float NOT NULL")]
		public double BEG_BAL
		{
			get
			{
				return this._BEG_BAL;
			}
			set
			{
				if ((this._BEG_BAL != value))
				{
					this.OnBEG_BALChanging(value);
					this.SendPropertyChanging();
					this._BEG_BAL = value;
					this.SendPropertyChanged("BEG_BAL");
					this.OnBEG_BALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENTS", DbType="Float")]
		public System.Nullable<double> CURRENTS
		{
			get
			{
				return this._CURRENTS;
			}
			set
			{
				if ((this._CURRENTS != value))
				{
					this.OnCURRENTSChanging(value);
					this.SendPropertyChanging();
					this._CURRENTS = value;
					this.SendPropertyChanged("CURRENTS");
					this.OnCURRENTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CR_LIMIT", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CR_LIMIT
		{
			get
			{
				return this._CR_LIMIT;
			}
			set
			{
				if ((this._CR_LIMIT != value))
				{
					this.OnCR_LIMITChanging(value);
					this.SendPropertyChanging();
					this._CR_LIMIT = value;
					this.SendPropertyChanged("CR_LIMIT");
					this.OnCR_LIMITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINANCE", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> FINANCE
		{
			get
			{
				return this._FINANCE;
			}
			set
			{
				if ((this._FINANCE != value))
				{
					this.OnFINANCEChanging(value);
					this.SendPropertyChanging();
					this._FINANCE = value;
					this.SendPropertyChanged("FINANCE");
					this.OnFINANCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERM", DbType="Int")]
		public System.Nullable<int> TERM
		{
			get
			{
				return this._TERM;
			}
			set
			{
				if ((this._TERM != value))
				{
					this.OnTERMChanging(value);
					this.SendPropertyChanging();
					this._TERM = value;
					this.SendPropertyChanged("TERM");
					this.OnTERMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Bit NOT NULL")]
		public bool STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KUNJUNGAN")]
	public partial class KUNJUNGAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _KD_PASIEN;
		
		private string _KD_UNIT;
		
		private System.DateTime _TGL_MASUK;
		
		private short _URUT_MASUK;
		
		private string _KD_DOKTER;
		
		private System.Nullable<int> _KD_RUJUKAN;
		
		private string _KD_CUSTOMER;
		
		private System.Nullable<System.DateTime> _JAM_MASUK;
		
		private System.Nullable<System.DateTime> _TGL_KELUAR;
		
		private System.Nullable<System.DateTime> _JAM_KELUAR;
		
		private byte _KEADAAN_MASUK;
		
		private byte _KEADAAN_PASIEN;
		
		private byte _CARA_PENERIMAAN;
		
		private byte _ASAL_PASIEN;
		
		private byte _CARA_KELUAR;
		
		private bool _BARU;
		
		private decimal _SHIFT;
		
		private byte _KARYAWAN;
		
		private bool _KONTROL;
		
		private string _SebabMati;
		
		private int _ANTRIAN;
		
		private string _NO_SURAT;
		
		private string _ALERGI;
		
		private string _CATATAN;
		
		private System.Nullable<byte> _WAKTU_MATI;
		
		private string _KET_MATI_OPR;
		
		private System.Nullable<byte> _STATUS_PERIKSA;
		
		private string _CAT_FISIK;
		
		private string _KD_LOKET;
		
		private string _TINDAKAN;
		
		private string _PERAWATAN;
		
		private string _STATUS_PULANG;
		
		private string _KETERANGAN_PLNG;
		
		private string _CATATAN_REHAB;
		
		private string _KD_TRIASE;
		
		private string _KD_KECELAKAAN;
		
		private string _NO_SJP;
		
		private System.Nullable<int> _intAntrian;
		
		private string _ANAMNESIS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKD_PASIENChanging(string value);
    partial void OnKD_PASIENChanged();
    partial void OnKD_UNITChanging(string value);
    partial void OnKD_UNITChanged();
    partial void OnTGL_MASUKChanging(System.DateTime value);
    partial void OnTGL_MASUKChanged();
    partial void OnURUT_MASUKChanging(short value);
    partial void OnURUT_MASUKChanged();
    partial void OnKD_DOKTERChanging(string value);
    partial void OnKD_DOKTERChanged();
    partial void OnKD_RUJUKANChanging(System.Nullable<int> value);
    partial void OnKD_RUJUKANChanged();
    partial void OnKD_CUSTOMERChanging(string value);
    partial void OnKD_CUSTOMERChanged();
    partial void OnJAM_MASUKChanging(System.Nullable<System.DateTime> value);
    partial void OnJAM_MASUKChanged();
    partial void OnTGL_KELUARChanging(System.Nullable<System.DateTime> value);
    partial void OnTGL_KELUARChanged();
    partial void OnJAM_KELUARChanging(System.Nullable<System.DateTime> value);
    partial void OnJAM_KELUARChanged();
    partial void OnKEADAAN_MASUKChanging(byte value);
    partial void OnKEADAAN_MASUKChanged();
    partial void OnKEADAAN_PASIENChanging(byte value);
    partial void OnKEADAAN_PASIENChanged();
    partial void OnCARA_PENERIMAANChanging(byte value);
    partial void OnCARA_PENERIMAANChanged();
    partial void OnASAL_PASIENChanging(byte value);
    partial void OnASAL_PASIENChanged();
    partial void OnCARA_KELUARChanging(byte value);
    partial void OnCARA_KELUARChanged();
    partial void OnBARUChanging(bool value);
    partial void OnBARUChanged();
    partial void OnSHIFTChanging(decimal value);
    partial void OnSHIFTChanged();
    partial void OnKARYAWANChanging(byte value);
    partial void OnKARYAWANChanged();
    partial void OnKONTROLChanging(bool value);
    partial void OnKONTROLChanged();
    partial void OnSebabMatiChanging(string value);
    partial void OnSebabMatiChanged();
    partial void OnANTRIANChanging(int value);
    partial void OnANTRIANChanged();
    partial void OnNO_SURATChanging(string value);
    partial void OnNO_SURATChanged();
    partial void OnALERGIChanging(string value);
    partial void OnALERGIChanged();
    partial void OnCATATANChanging(string value);
    partial void OnCATATANChanged();
    partial void OnWAKTU_MATIChanging(System.Nullable<byte> value);
    partial void OnWAKTU_MATIChanged();
    partial void OnKET_MATI_OPRChanging(string value);
    partial void OnKET_MATI_OPRChanged();
    partial void OnSTATUS_PERIKSAChanging(System.Nullable<byte> value);
    partial void OnSTATUS_PERIKSAChanged();
    partial void OnCAT_FISIKChanging(string value);
    partial void OnCAT_FISIKChanged();
    partial void OnKD_LOKETChanging(string value);
    partial void OnKD_LOKETChanged();
    partial void OnTINDAKANChanging(string value);
    partial void OnTINDAKANChanged();
    partial void OnPERAWATANChanging(string value);
    partial void OnPERAWATANChanged();
    partial void OnSTATUS_PULANGChanging(string value);
    partial void OnSTATUS_PULANGChanged();
    partial void OnKETERANGAN_PLNGChanging(string value);
    partial void OnKETERANGAN_PLNGChanged();
    partial void OnCATATAN_REHABChanging(string value);
    partial void OnCATATAN_REHABChanged();
    partial void OnKD_TRIASEChanging(string value);
    partial void OnKD_TRIASEChanged();
    partial void OnKD_KECELAKAANChanging(string value);
    partial void OnKD_KECELAKAANChanged();
    partial void OnNO_SJPChanging(string value);
    partial void OnNO_SJPChanged();
    partial void OnintAntrianChanging(System.Nullable<int> value);
    partial void OnintAntrianChanged();
    partial void OnANAMNESISChanging(string value);
    partial void OnANAMNESISChanged();
    #endregion
		
		public KUNJUNGAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_PASIEN", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string KD_PASIEN
		{
			get
			{
				return this._KD_PASIEN;
			}
			set
			{
				if ((this._KD_PASIEN != value))
				{
					this.OnKD_PASIENChanging(value);
					this.SendPropertyChanging();
					this._KD_PASIEN = value;
					this.SendPropertyChanged("KD_PASIEN");
					this.OnKD_PASIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_UNIT", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string KD_UNIT
		{
			get
			{
				return this._KD_UNIT;
			}
			set
			{
				if ((this._KD_UNIT != value))
				{
					this.OnKD_UNITChanging(value);
					this.SendPropertyChanging();
					this._KD_UNIT = value;
					this.SendPropertyChanged("KD_UNIT");
					this.OnKD_UNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGL_MASUK", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime TGL_MASUK
		{
			get
			{
				return this._TGL_MASUK;
			}
			set
			{
				if ((this._TGL_MASUK != value))
				{
					this.OnTGL_MASUKChanging(value);
					this.SendPropertyChanging();
					this._TGL_MASUK = value;
					this.SendPropertyChanged("TGL_MASUK");
					this.OnTGL_MASUKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URUT_MASUK", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short URUT_MASUK
		{
			get
			{
				return this._URUT_MASUK;
			}
			set
			{
				if ((this._URUT_MASUK != value))
				{
					this.OnURUT_MASUKChanging(value);
					this.SendPropertyChanging();
					this._URUT_MASUK = value;
					this.SendPropertyChanged("URUT_MASUK");
					this.OnURUT_MASUKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_DOKTER", DbType="VarChar(3)")]
		public string KD_DOKTER
		{
			get
			{
				return this._KD_DOKTER;
			}
			set
			{
				if ((this._KD_DOKTER != value))
				{
					this.OnKD_DOKTERChanging(value);
					this.SendPropertyChanging();
					this._KD_DOKTER = value;
					this.SendPropertyChanged("KD_DOKTER");
					this.OnKD_DOKTERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_RUJUKAN", DbType="Int")]
		public System.Nullable<int> KD_RUJUKAN
		{
			get
			{
				return this._KD_RUJUKAN;
			}
			set
			{
				if ((this._KD_RUJUKAN != value))
				{
					this.OnKD_RUJUKANChanging(value);
					this.SendPropertyChanging();
					this._KD_RUJUKAN = value;
					this.SendPropertyChanged("KD_RUJUKAN");
					this.OnKD_RUJUKANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_CUSTOMER", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string KD_CUSTOMER
		{
			get
			{
				return this._KD_CUSTOMER;
			}
			set
			{
				if ((this._KD_CUSTOMER != value))
				{
					this.OnKD_CUSTOMERChanging(value);
					this.SendPropertyChanging();
					this._KD_CUSTOMER = value;
					this.SendPropertyChanged("KD_CUSTOMER");
					this.OnKD_CUSTOMERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JAM_MASUK", DbType="DateTime")]
		public System.Nullable<System.DateTime> JAM_MASUK
		{
			get
			{
				return this._JAM_MASUK;
			}
			set
			{
				if ((this._JAM_MASUK != value))
				{
					this.OnJAM_MASUKChanging(value);
					this.SendPropertyChanging();
					this._JAM_MASUK = value;
					this.SendPropertyChanged("JAM_MASUK");
					this.OnJAM_MASUKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGL_KELUAR", DbType="DateTime")]
		public System.Nullable<System.DateTime> TGL_KELUAR
		{
			get
			{
				return this._TGL_KELUAR;
			}
			set
			{
				if ((this._TGL_KELUAR != value))
				{
					this.OnTGL_KELUARChanging(value);
					this.SendPropertyChanging();
					this._TGL_KELUAR = value;
					this.SendPropertyChanged("TGL_KELUAR");
					this.OnTGL_KELUARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JAM_KELUAR", DbType="DateTime")]
		public System.Nullable<System.DateTime> JAM_KELUAR
		{
			get
			{
				return this._JAM_KELUAR;
			}
			set
			{
				if ((this._JAM_KELUAR != value))
				{
					this.OnJAM_KELUARChanging(value);
					this.SendPropertyChanging();
					this._JAM_KELUAR = value;
					this.SendPropertyChanged("JAM_KELUAR");
					this.OnJAM_KELUARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEADAAN_MASUK", DbType="TinyInt NOT NULL")]
		public byte KEADAAN_MASUK
		{
			get
			{
				return this._KEADAAN_MASUK;
			}
			set
			{
				if ((this._KEADAAN_MASUK != value))
				{
					this.OnKEADAAN_MASUKChanging(value);
					this.SendPropertyChanging();
					this._KEADAAN_MASUK = value;
					this.SendPropertyChanged("KEADAAN_MASUK");
					this.OnKEADAAN_MASUKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEADAAN_PASIEN", DbType="TinyInt NOT NULL")]
		public byte KEADAAN_PASIEN
		{
			get
			{
				return this._KEADAAN_PASIEN;
			}
			set
			{
				if ((this._KEADAAN_PASIEN != value))
				{
					this.OnKEADAAN_PASIENChanging(value);
					this.SendPropertyChanging();
					this._KEADAAN_PASIEN = value;
					this.SendPropertyChanged("KEADAAN_PASIEN");
					this.OnKEADAAN_PASIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARA_PENERIMAAN", DbType="TinyInt NOT NULL")]
		public byte CARA_PENERIMAAN
		{
			get
			{
				return this._CARA_PENERIMAAN;
			}
			set
			{
				if ((this._CARA_PENERIMAAN != value))
				{
					this.OnCARA_PENERIMAANChanging(value);
					this.SendPropertyChanging();
					this._CARA_PENERIMAAN = value;
					this.SendPropertyChanged("CARA_PENERIMAAN");
					this.OnCARA_PENERIMAANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASAL_PASIEN", DbType="TinyInt NOT NULL")]
		public byte ASAL_PASIEN
		{
			get
			{
				return this._ASAL_PASIEN;
			}
			set
			{
				if ((this._ASAL_PASIEN != value))
				{
					this.OnASAL_PASIENChanging(value);
					this.SendPropertyChanging();
					this._ASAL_PASIEN = value;
					this.SendPropertyChanged("ASAL_PASIEN");
					this.OnASAL_PASIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARA_KELUAR", DbType="TinyInt NOT NULL")]
		public byte CARA_KELUAR
		{
			get
			{
				return this._CARA_KELUAR;
			}
			set
			{
				if ((this._CARA_KELUAR != value))
				{
					this.OnCARA_KELUARChanging(value);
					this.SendPropertyChanging();
					this._CARA_KELUAR = value;
					this.SendPropertyChanged("CARA_KELUAR");
					this.OnCARA_KELUARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARU", DbType="Bit NOT NULL")]
		public bool BARU
		{
			get
			{
				return this._BARU;
			}
			set
			{
				if ((this._BARU != value))
				{
					this.OnBARUChanging(value);
					this.SendPropertyChanging();
					this._BARU = value;
					this.SendPropertyChanged("BARU");
					this.OnBARUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHIFT", DbType="Decimal(1,0) NOT NULL")]
		public decimal SHIFT
		{
			get
			{
				return this._SHIFT;
			}
			set
			{
				if ((this._SHIFT != value))
				{
					this.OnSHIFTChanging(value);
					this.SendPropertyChanging();
					this._SHIFT = value;
					this.SendPropertyChanged("SHIFT");
					this.OnSHIFTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KARYAWAN", DbType="TinyInt NOT NULL")]
		public byte KARYAWAN
		{
			get
			{
				return this._KARYAWAN;
			}
			set
			{
				if ((this._KARYAWAN != value))
				{
					this.OnKARYAWANChanging(value);
					this.SendPropertyChanging();
					this._KARYAWAN = value;
					this.SendPropertyChanged("KARYAWAN");
					this.OnKARYAWANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KONTROL", DbType="Bit NOT NULL")]
		public bool KONTROL
		{
			get
			{
				return this._KONTROL;
			}
			set
			{
				if ((this._KONTROL != value))
				{
					this.OnKONTROLChanging(value);
					this.SendPropertyChanging();
					this._KONTROL = value;
					this.SendPropertyChanged("KONTROL");
					this.OnKONTROLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SebabMati", DbType="VarChar(30)")]
		public string SebabMati
		{
			get
			{
				return this._SebabMati;
			}
			set
			{
				if ((this._SebabMati != value))
				{
					this.OnSebabMatiChanging(value);
					this.SendPropertyChanging();
					this._SebabMati = value;
					this.SendPropertyChanged("SebabMati");
					this.OnSebabMatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANTRIAN", DbType="Int NOT NULL")]
		public int ANTRIAN
		{
			get
			{
				return this._ANTRIAN;
			}
			set
			{
				if ((this._ANTRIAN != value))
				{
					this.OnANTRIANChanging(value);
					this.SendPropertyChanging();
					this._ANTRIAN = value;
					this.SendPropertyChanged("ANTRIAN");
					this.OnANTRIANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_SURAT", DbType="VarChar(30)")]
		public string NO_SURAT
		{
			get
			{
				return this._NO_SURAT;
			}
			set
			{
				if ((this._NO_SURAT != value))
				{
					this.OnNO_SURATChanging(value);
					this.SendPropertyChanging();
					this._NO_SURAT = value;
					this.SendPropertyChanged("NO_SURAT");
					this.OnNO_SURATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALERGI", DbType="VarChar(30)")]
		public string ALERGI
		{
			get
			{
				return this._ALERGI;
			}
			set
			{
				if ((this._ALERGI != value))
				{
					this.OnALERGIChanging(value);
					this.SendPropertyChanging();
					this._ALERGI = value;
					this.SendPropertyChanged("ALERGI");
					this.OnALERGIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATATAN", DbType="VarChar(300)")]
		public string CATATAN
		{
			get
			{
				return this._CATATAN;
			}
			set
			{
				if ((this._CATATAN != value))
				{
					this.OnCATATANChanging(value);
					this.SendPropertyChanging();
					this._CATATAN = value;
					this.SendPropertyChanged("CATATAN");
					this.OnCATATANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WAKTU_MATI", DbType="TinyInt")]
		public System.Nullable<byte> WAKTU_MATI
		{
			get
			{
				return this._WAKTU_MATI;
			}
			set
			{
				if ((this._WAKTU_MATI != value))
				{
					this.OnWAKTU_MATIChanging(value);
					this.SendPropertyChanging();
					this._WAKTU_MATI = value;
					this.SendPropertyChanged("WAKTU_MATI");
					this.OnWAKTU_MATIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KET_MATI_OPR", DbType="VarChar(100)")]
		public string KET_MATI_OPR
		{
			get
			{
				return this._KET_MATI_OPR;
			}
			set
			{
				if ((this._KET_MATI_OPR != value))
				{
					this.OnKET_MATI_OPRChanging(value);
					this.SendPropertyChanging();
					this._KET_MATI_OPR = value;
					this.SendPropertyChanged("KET_MATI_OPR");
					this.OnKET_MATI_OPRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_PERIKSA", DbType="TinyInt")]
		public System.Nullable<byte> STATUS_PERIKSA
		{
			get
			{
				return this._STATUS_PERIKSA;
			}
			set
			{
				if ((this._STATUS_PERIKSA != value))
				{
					this.OnSTATUS_PERIKSAChanging(value);
					this.SendPropertyChanging();
					this._STATUS_PERIKSA = value;
					this.SendPropertyChanged("STATUS_PERIKSA");
					this.OnSTATUS_PERIKSAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAT_FISIK", DbType="VarChar(300)")]
		public string CAT_FISIK
		{
			get
			{
				return this._CAT_FISIK;
			}
			set
			{
				if ((this._CAT_FISIK != value))
				{
					this.OnCAT_FISIKChanging(value);
					this.SendPropertyChanging();
					this._CAT_FISIK = value;
					this.SendPropertyChanged("CAT_FISIK");
					this.OnCAT_FISIKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_LOKET", DbType="VarChar(4)")]
		public string KD_LOKET
		{
			get
			{
				return this._KD_LOKET;
			}
			set
			{
				if ((this._KD_LOKET != value))
				{
					this.OnKD_LOKETChanging(value);
					this.SendPropertyChanging();
					this._KD_LOKET = value;
					this.SendPropertyChanged("KD_LOKET");
					this.OnKD_LOKETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINDAKAN", DbType="VarChar(10)")]
		public string TINDAKAN
		{
			get
			{
				return this._TINDAKAN;
			}
			set
			{
				if ((this._TINDAKAN != value))
				{
					this.OnTINDAKANChanging(value);
					this.SendPropertyChanging();
					this._TINDAKAN = value;
					this.SendPropertyChanged("TINDAKAN");
					this.OnTINDAKANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERAWATAN", DbType="VarChar(10)")]
		public string PERAWATAN
		{
			get
			{
				return this._PERAWATAN;
			}
			set
			{
				if ((this._PERAWATAN != value))
				{
					this.OnPERAWATANChanging(value);
					this.SendPropertyChanging();
					this._PERAWATAN = value;
					this.SendPropertyChanged("PERAWATAN");
					this.OnPERAWATANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_PULANG", DbType="VarChar(50)")]
		public string STATUS_PULANG
		{
			get
			{
				return this._STATUS_PULANG;
			}
			set
			{
				if ((this._STATUS_PULANG != value))
				{
					this.OnSTATUS_PULANGChanging(value);
					this.SendPropertyChanging();
					this._STATUS_PULANG = value;
					this.SendPropertyChanged("STATUS_PULANG");
					this.OnSTATUS_PULANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KETERANGAN_PLNG", DbType="VarChar(50)")]
		public string KETERANGAN_PLNG
		{
			get
			{
				return this._KETERANGAN_PLNG;
			}
			set
			{
				if ((this._KETERANGAN_PLNG != value))
				{
					this.OnKETERANGAN_PLNGChanging(value);
					this.SendPropertyChanging();
					this._KETERANGAN_PLNG = value;
					this.SendPropertyChanged("KETERANGAN_PLNG");
					this.OnKETERANGAN_PLNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATATAN_REHAB", DbType="VarChar(800)")]
		public string CATATAN_REHAB
		{
			get
			{
				return this._CATATAN_REHAB;
			}
			set
			{
				if ((this._CATATAN_REHAB != value))
				{
					this.OnCATATAN_REHABChanging(value);
					this.SendPropertyChanging();
					this._CATATAN_REHAB = value;
					this.SendPropertyChanged("CATATAN_REHAB");
					this.OnCATATAN_REHABChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_TRIASE", DbType="VarChar(2)")]
		public string KD_TRIASE
		{
			get
			{
				return this._KD_TRIASE;
			}
			set
			{
				if ((this._KD_TRIASE != value))
				{
					this.OnKD_TRIASEChanging(value);
					this.SendPropertyChanging();
					this._KD_TRIASE = value;
					this.SendPropertyChanged("KD_TRIASE");
					this.OnKD_TRIASEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_KECELAKAAN", DbType="VarChar(2)")]
		public string KD_KECELAKAAN
		{
			get
			{
				return this._KD_KECELAKAAN;
			}
			set
			{
				if ((this._KD_KECELAKAAN != value))
				{
					this.OnKD_KECELAKAANChanging(value);
					this.SendPropertyChanging();
					this._KD_KECELAKAAN = value;
					this.SendPropertyChanged("KD_KECELAKAAN");
					this.OnKD_KECELAKAANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_SJP", DbType="VarChar(20)")]
		public string NO_SJP
		{
			get
			{
				return this._NO_SJP;
			}
			set
			{
				if ((this._NO_SJP != value))
				{
					this.OnNO_SJPChanging(value);
					this.SendPropertyChanging();
					this._NO_SJP = value;
					this.SendPropertyChanged("NO_SJP");
					this.OnNO_SJPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intAntrian", DbType="Int")]
		public System.Nullable<int> intAntrian
		{
			get
			{
				return this._intAntrian;
			}
			set
			{
				if ((this._intAntrian != value))
				{
					this.OnintAntrianChanging(value);
					this.SendPropertyChanging();
					this._intAntrian = value;
					this.SendPropertyChanged("intAntrian");
					this.OnintAntrianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANAMNESIS", DbType="VarChar(100)")]
		public string ANAMNESIS
		{
			get
			{
				return this._ANAMNESIS;
			}
			set
			{
				if ((this._ANAMNESIS != value))
				{
					this.OnANAMNESISChanging(value);
					this.SendPropertyChanging();
					this._ANAMNESIS = value;
					this.SendPropertyChanged("ANAMNESIS");
					this.OnANAMNESISChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KAMAR_INDUK")]
	public partial class KAMAR_INDUK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NO_KAMAR;
		
		private string _NAMA_KAMAR;
		
		private int _JUMLAH_BED;
		
		private int _DIGUNAKAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNO_KAMARChanging(string value);
    partial void OnNO_KAMARChanged();
    partial void OnNAMA_KAMARChanging(string value);
    partial void OnNAMA_KAMARChanged();
    partial void OnJUMLAH_BEDChanging(int value);
    partial void OnJUMLAH_BEDChanged();
    partial void OnDIGUNAKANChanging(int value);
    partial void OnDIGUNAKANChanged();
    #endregion
		
		public KAMAR_INDUK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_KAMAR", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NO_KAMAR
		{
			get
			{
				return this._NO_KAMAR;
			}
			set
			{
				if ((this._NO_KAMAR != value))
				{
					this.OnNO_KAMARChanging(value);
					this.SendPropertyChanging();
					this._NO_KAMAR = value;
					this.SendPropertyChanged("NO_KAMAR");
					this.OnNO_KAMARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_KAMAR", DbType="VarChar(30)")]
		public string NAMA_KAMAR
		{
			get
			{
				return this._NAMA_KAMAR;
			}
			set
			{
				if ((this._NAMA_KAMAR != value))
				{
					this.OnNAMA_KAMARChanging(value);
					this.SendPropertyChanging();
					this._NAMA_KAMAR = value;
					this.SendPropertyChanged("NAMA_KAMAR");
					this.OnNAMA_KAMARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JUMLAH_BED", DbType="Int NOT NULL")]
		public int JUMLAH_BED
		{
			get
			{
				return this._JUMLAH_BED;
			}
			set
			{
				if ((this._JUMLAH_BED != value))
				{
					this.OnJUMLAH_BEDChanging(value);
					this.SendPropertyChanging();
					this._JUMLAH_BED = value;
					this.SendPropertyChanged("JUMLAH_BED");
					this.OnJUMLAH_BEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIGUNAKAN", DbType="Int NOT NULL")]
		public int DIGUNAKAN
		{
			get
			{
				return this._DIGUNAKAN;
			}
			set
			{
				if ((this._DIGUNAKAN != value))
				{
					this.OnDIGUNAKANChanging(value);
					this.SendPropertyChanging();
					this._DIGUNAKAN = value;
					this.SendPropertyChanged("DIGUNAKAN");
					this.OnDIGUNAKANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGINAP")]
	public partial class NGINAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _KD_UNIT_KAMAR;
		
		private string _NO_KAMAR;
		
		private string _KD_PASIEN;
		
		private string _KD_UNIT;
		
		private System.DateTime _TGL_MASUK;
		
		private short _URUT_MASUK;
		
		private System.DateTime _TGL_INAP;
		
		private System.DateTime _JAM_INAP;
		
		private System.Nullable<System.DateTime> _TGL_KELUAR;
		
		private System.Nullable<System.DateTime> _JAM_KELUAR;
		
		private string _BED;
		
		private byte _KD_SPESIAL;
		
		private bool _AKHIR;
		
		private short _URUT_NGINAP;
		
		private string _ALASAN_PINDAH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKD_UNIT_KAMARChanging(string value);
    partial void OnKD_UNIT_KAMARChanged();
    partial void OnNO_KAMARChanging(string value);
    partial void OnNO_KAMARChanged();
    partial void OnKD_PASIENChanging(string value);
    partial void OnKD_PASIENChanged();
    partial void OnKD_UNITChanging(string value);
    partial void OnKD_UNITChanged();
    partial void OnTGL_MASUKChanging(System.DateTime value);
    partial void OnTGL_MASUKChanged();
    partial void OnURUT_MASUKChanging(short value);
    partial void OnURUT_MASUKChanged();
    partial void OnTGL_INAPChanging(System.DateTime value);
    partial void OnTGL_INAPChanged();
    partial void OnJAM_INAPChanging(System.DateTime value);
    partial void OnJAM_INAPChanged();
    partial void OnTGL_KELUARChanging(System.Nullable<System.DateTime> value);
    partial void OnTGL_KELUARChanged();
    partial void OnJAM_KELUARChanging(System.Nullable<System.DateTime> value);
    partial void OnJAM_KELUARChanged();
    partial void OnBEDChanging(string value);
    partial void OnBEDChanged();
    partial void OnKD_SPESIALChanging(byte value);
    partial void OnKD_SPESIALChanged();
    partial void OnAKHIRChanging(bool value);
    partial void OnAKHIRChanged();
    partial void OnURUT_NGINAPChanging(short value);
    partial void OnURUT_NGINAPChanged();
    partial void OnALASAN_PINDAHChanging(string value);
    partial void OnALASAN_PINDAHChanged();
    #endregion
		
		public NGINAP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_UNIT_KAMAR", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string KD_UNIT_KAMAR
		{
			get
			{
				return this._KD_UNIT_KAMAR;
			}
			set
			{
				if ((this._KD_UNIT_KAMAR != value))
				{
					this.OnKD_UNIT_KAMARChanging(value);
					this.SendPropertyChanging();
					this._KD_UNIT_KAMAR = value;
					this.SendPropertyChanged("KD_UNIT_KAMAR");
					this.OnKD_UNIT_KAMARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_KAMAR", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NO_KAMAR
		{
			get
			{
				return this._NO_KAMAR;
			}
			set
			{
				if ((this._NO_KAMAR != value))
				{
					this.OnNO_KAMARChanging(value);
					this.SendPropertyChanging();
					this._NO_KAMAR = value;
					this.SendPropertyChanged("NO_KAMAR");
					this.OnNO_KAMARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_PASIEN", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string KD_PASIEN
		{
			get
			{
				return this._KD_PASIEN;
			}
			set
			{
				if ((this._KD_PASIEN != value))
				{
					this.OnKD_PASIENChanging(value);
					this.SendPropertyChanging();
					this._KD_PASIEN = value;
					this.SendPropertyChanged("KD_PASIEN");
					this.OnKD_PASIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_UNIT", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string KD_UNIT
		{
			get
			{
				return this._KD_UNIT;
			}
			set
			{
				if ((this._KD_UNIT != value))
				{
					this.OnKD_UNITChanging(value);
					this.SendPropertyChanging();
					this._KD_UNIT = value;
					this.SendPropertyChanged("KD_UNIT");
					this.OnKD_UNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGL_MASUK", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime TGL_MASUK
		{
			get
			{
				return this._TGL_MASUK;
			}
			set
			{
				if ((this._TGL_MASUK != value))
				{
					this.OnTGL_MASUKChanging(value);
					this.SendPropertyChanging();
					this._TGL_MASUK = value;
					this.SendPropertyChanged("TGL_MASUK");
					this.OnTGL_MASUKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URUT_MASUK", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short URUT_MASUK
		{
			get
			{
				return this._URUT_MASUK;
			}
			set
			{
				if ((this._URUT_MASUK != value))
				{
					this.OnURUT_MASUKChanging(value);
					this.SendPropertyChanging();
					this._URUT_MASUK = value;
					this.SendPropertyChanged("URUT_MASUK");
					this.OnURUT_MASUKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGL_INAP", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime TGL_INAP
		{
			get
			{
				return this._TGL_INAP;
			}
			set
			{
				if ((this._TGL_INAP != value))
				{
					this.OnTGL_INAPChanging(value);
					this.SendPropertyChanging();
					this._TGL_INAP = value;
					this.SendPropertyChanged("TGL_INAP");
					this.OnTGL_INAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JAM_INAP", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime JAM_INAP
		{
			get
			{
				return this._JAM_INAP;
			}
			set
			{
				if ((this._JAM_INAP != value))
				{
					this.OnJAM_INAPChanging(value);
					this.SendPropertyChanging();
					this._JAM_INAP = value;
					this.SendPropertyChanged("JAM_INAP");
					this.OnJAM_INAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGL_KELUAR", DbType="DateTime")]
		public System.Nullable<System.DateTime> TGL_KELUAR
		{
			get
			{
				return this._TGL_KELUAR;
			}
			set
			{
				if ((this._TGL_KELUAR != value))
				{
					this.OnTGL_KELUARChanging(value);
					this.SendPropertyChanging();
					this._TGL_KELUAR = value;
					this.SendPropertyChanged("TGL_KELUAR");
					this.OnTGL_KELUARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JAM_KELUAR", DbType="DateTime")]
		public System.Nullable<System.DateTime> JAM_KELUAR
		{
			get
			{
				return this._JAM_KELUAR;
			}
			set
			{
				if ((this._JAM_KELUAR != value))
				{
					this.OnJAM_KELUARChanging(value);
					this.SendPropertyChanging();
					this._JAM_KELUAR = value;
					this.SendPropertyChanged("JAM_KELUAR");
					this.OnJAM_KELUARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BED", DbType="VarChar(3)")]
		public string BED
		{
			get
			{
				return this._BED;
			}
			set
			{
				if ((this._BED != value))
				{
					this.OnBEDChanging(value);
					this.SendPropertyChanging();
					this._BED = value;
					this.SendPropertyChanged("BED");
					this.OnBEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_SPESIAL", DbType="TinyInt NOT NULL")]
		public byte KD_SPESIAL
		{
			get
			{
				return this._KD_SPESIAL;
			}
			set
			{
				if ((this._KD_SPESIAL != value))
				{
					this.OnKD_SPESIALChanging(value);
					this.SendPropertyChanging();
					this._KD_SPESIAL = value;
					this.SendPropertyChanged("KD_SPESIAL");
					this.OnKD_SPESIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AKHIR", DbType="Bit NOT NULL")]
		public bool AKHIR
		{
			get
			{
				return this._AKHIR;
			}
			set
			{
				if ((this._AKHIR != value))
				{
					this.OnAKHIRChanging(value);
					this.SendPropertyChanging();
					this._AKHIR = value;
					this.SendPropertyChanged("AKHIR");
					this.OnAKHIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URUT_NGINAP", DbType="SmallInt NOT NULL")]
		public short URUT_NGINAP
		{
			get
			{
				return this._URUT_NGINAP;
			}
			set
			{
				if ((this._URUT_NGINAP != value))
				{
					this.OnURUT_NGINAPChanging(value);
					this.SendPropertyChanging();
					this._URUT_NGINAP = value;
					this.SendPropertyChanged("URUT_NGINAP");
					this.OnURUT_NGINAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALASAN_PINDAH", DbType="VarChar(35)")]
		public string ALASAN_PINDAH
		{
			get
			{
				return this._ALASAN_PINDAH;
			}
			set
			{
				if ((this._ALASAN_PINDAH != value))
				{
					this.OnALASAN_PINDAHChanging(value);
					this.SendPropertyChanging();
					this._ALASAN_PINDAH = value;
					this.SendPropertyChanged("ALASAN_PINDAH");
					this.OnALASAN_PINDAHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PASIEN_INAP")]
	public partial class PASIEN_INAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _KD_KASIR;
		
		private string _NO_TRANSAKSI;
		
		private string _KD_UNIT;
		
		private string _NO_KAMAR;
		
		private System.Nullable<byte> _KD_SPESIAL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKD_KASIRChanging(string value);
    partial void OnKD_KASIRChanged();
    partial void OnNO_TRANSAKSIChanging(string value);
    partial void OnNO_TRANSAKSIChanged();
    partial void OnKD_UNITChanging(string value);
    partial void OnKD_UNITChanged();
    partial void OnNO_KAMARChanging(string value);
    partial void OnNO_KAMARChanged();
    partial void OnKD_SPESIALChanging(System.Nullable<byte> value);
    partial void OnKD_SPESIALChanged();
    #endregion
		
		public PASIEN_INAP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_KASIR", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string KD_KASIR
		{
			get
			{
				return this._KD_KASIR;
			}
			set
			{
				if ((this._KD_KASIR != value))
				{
					this.OnKD_KASIRChanging(value);
					this.SendPropertyChanging();
					this._KD_KASIR = value;
					this.SendPropertyChanged("KD_KASIR");
					this.OnKD_KASIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_TRANSAKSI", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NO_TRANSAKSI
		{
			get
			{
				return this._NO_TRANSAKSI;
			}
			set
			{
				if ((this._NO_TRANSAKSI != value))
				{
					this.OnNO_TRANSAKSIChanging(value);
					this.SendPropertyChanging();
					this._NO_TRANSAKSI = value;
					this.SendPropertyChanged("NO_TRANSAKSI");
					this.OnNO_TRANSAKSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_UNIT", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string KD_UNIT
		{
			get
			{
				return this._KD_UNIT;
			}
			set
			{
				if ((this._KD_UNIT != value))
				{
					this.OnKD_UNITChanging(value);
					this.SendPropertyChanging();
					this._KD_UNIT = value;
					this.SendPropertyChanged("KD_UNIT");
					this.OnKD_UNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_KAMAR", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string NO_KAMAR
		{
			get
			{
				return this._NO_KAMAR;
			}
			set
			{
				if ((this._NO_KAMAR != value))
				{
					this.OnNO_KAMARChanging(value);
					this.SendPropertyChanging();
					this._NO_KAMAR = value;
					this.SendPropertyChanged("NO_KAMAR");
					this.OnNO_KAMARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_SPESIAL", DbType="TinyInt")]
		public System.Nullable<byte> KD_SPESIAL
		{
			get
			{
				return this._KD_SPESIAL;
			}
			set
			{
				if ((this._KD_SPESIAL != value))
				{
					this.OnKD_SPESIALChanging(value);
					this.SendPropertyChanging();
					this._KD_SPESIAL = value;
					this.SendPropertyChanged("KD_SPESIAL");
					this.OnKD_SPESIALChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRANSAKSI")]
	public partial class TRANSAKSI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _KD_KASIR;
		
		private string _NO_TRANSAKSI;
		
		private string _KD_PASIEN;
		
		private string _KD_UNIT;
		
		private System.DateTime _TGL_TRANSAKSI;
		
		private short _URUT_MASUK;
		
		private System.Nullable<System.DateTime> _TGL_CO;
		
		private bool _CO_STATUS;
		
		private System.Nullable<int> _ORDERLIST;
		
		private bool _ISPAY;
		
		private bool _APP;
		
		private System.Nullable<int> _KD_USER;
		
		private string _TAG;
		
		private bool _LUNAS;
		
		private System.Nullable<System.DateTime> _TGL_LUNAS;
		
		private bool _ACC_DR;
		
		private string _OrderMng;
		
		private System.Data.Linq.Binary _Dilayani;
		
		private System.Nullable<int> _verified;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKD_KASIRChanging(string value);
    partial void OnKD_KASIRChanged();
    partial void OnNO_TRANSAKSIChanging(string value);
    partial void OnNO_TRANSAKSIChanged();
    partial void OnKD_PASIENChanging(string value);
    partial void OnKD_PASIENChanged();
    partial void OnKD_UNITChanging(string value);
    partial void OnKD_UNITChanged();
    partial void OnTGL_TRANSAKSIChanging(System.DateTime value);
    partial void OnTGL_TRANSAKSIChanged();
    partial void OnURUT_MASUKChanging(short value);
    partial void OnURUT_MASUKChanged();
    partial void OnTGL_COChanging(System.Nullable<System.DateTime> value);
    partial void OnTGL_COChanged();
    partial void OnCO_STATUSChanging(bool value);
    partial void OnCO_STATUSChanged();
    partial void OnORDERLISTChanging(System.Nullable<int> value);
    partial void OnORDERLISTChanged();
    partial void OnISPAYChanging(bool value);
    partial void OnISPAYChanged();
    partial void OnAPPChanging(bool value);
    partial void OnAPPChanged();
    partial void OnKD_USERChanging(System.Nullable<int> value);
    partial void OnKD_USERChanged();
    partial void OnTAGChanging(string value);
    partial void OnTAGChanged();
    partial void OnLUNASChanging(bool value);
    partial void OnLUNASChanged();
    partial void OnTGL_LUNASChanging(System.Nullable<System.DateTime> value);
    partial void OnTGL_LUNASChanged();
    partial void OnACC_DRChanging(bool value);
    partial void OnACC_DRChanged();
    partial void OnOrderMngChanging(string value);
    partial void OnOrderMngChanged();
    partial void OnDilayaniChanging(System.Data.Linq.Binary value);
    partial void OnDilayaniChanged();
    partial void OnverifiedChanging(System.Nullable<int> value);
    partial void OnverifiedChanged();
    #endregion
		
		public TRANSAKSI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_KASIR", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string KD_KASIR
		{
			get
			{
				return this._KD_KASIR;
			}
			set
			{
				if ((this._KD_KASIR != value))
				{
					this.OnKD_KASIRChanging(value);
					this.SendPropertyChanging();
					this._KD_KASIR = value;
					this.SendPropertyChanged("KD_KASIR");
					this.OnKD_KASIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_TRANSAKSI", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NO_TRANSAKSI
		{
			get
			{
				return this._NO_TRANSAKSI;
			}
			set
			{
				if ((this._NO_TRANSAKSI != value))
				{
					this.OnNO_TRANSAKSIChanging(value);
					this.SendPropertyChanging();
					this._NO_TRANSAKSI = value;
					this.SendPropertyChanged("NO_TRANSAKSI");
					this.OnNO_TRANSAKSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_PASIEN", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string KD_PASIEN
		{
			get
			{
				return this._KD_PASIEN;
			}
			set
			{
				if ((this._KD_PASIEN != value))
				{
					this.OnKD_PASIENChanging(value);
					this.SendPropertyChanging();
					this._KD_PASIEN = value;
					this.SendPropertyChanged("KD_PASIEN");
					this.OnKD_PASIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_UNIT", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string KD_UNIT
		{
			get
			{
				return this._KD_UNIT;
			}
			set
			{
				if ((this._KD_UNIT != value))
				{
					this.OnKD_UNITChanging(value);
					this.SendPropertyChanging();
					this._KD_UNIT = value;
					this.SendPropertyChanged("KD_UNIT");
					this.OnKD_UNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGL_TRANSAKSI", DbType="DateTime NOT NULL")]
		public System.DateTime TGL_TRANSAKSI
		{
			get
			{
				return this._TGL_TRANSAKSI;
			}
			set
			{
				if ((this._TGL_TRANSAKSI != value))
				{
					this.OnTGL_TRANSAKSIChanging(value);
					this.SendPropertyChanging();
					this._TGL_TRANSAKSI = value;
					this.SendPropertyChanged("TGL_TRANSAKSI");
					this.OnTGL_TRANSAKSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URUT_MASUK", DbType="SmallInt NOT NULL")]
		public short URUT_MASUK
		{
			get
			{
				return this._URUT_MASUK;
			}
			set
			{
				if ((this._URUT_MASUK != value))
				{
					this.OnURUT_MASUKChanging(value);
					this.SendPropertyChanging();
					this._URUT_MASUK = value;
					this.SendPropertyChanged("URUT_MASUK");
					this.OnURUT_MASUKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGL_CO", DbType="DateTime")]
		public System.Nullable<System.DateTime> TGL_CO
		{
			get
			{
				return this._TGL_CO;
			}
			set
			{
				if ((this._TGL_CO != value))
				{
					this.OnTGL_COChanging(value);
					this.SendPropertyChanging();
					this._TGL_CO = value;
					this.SendPropertyChanged("TGL_CO");
					this.OnTGL_COChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CO_STATUS", DbType="Bit NOT NULL")]
		public bool CO_STATUS
		{
			get
			{
				return this._CO_STATUS;
			}
			set
			{
				if ((this._CO_STATUS != value))
				{
					this.OnCO_STATUSChanging(value);
					this.SendPropertyChanging();
					this._CO_STATUS = value;
					this.SendPropertyChanged("CO_STATUS");
					this.OnCO_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDERLIST", DbType="Int")]
		public System.Nullable<int> ORDERLIST
		{
			get
			{
				return this._ORDERLIST;
			}
			set
			{
				if ((this._ORDERLIST != value))
				{
					this.OnORDERLISTChanging(value);
					this.SendPropertyChanging();
					this._ORDERLIST = value;
					this.SendPropertyChanged("ORDERLIST");
					this.OnORDERLISTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISPAY", DbType="Bit NOT NULL")]
		public bool ISPAY
		{
			get
			{
				return this._ISPAY;
			}
			set
			{
				if ((this._ISPAY != value))
				{
					this.OnISPAYChanging(value);
					this.SendPropertyChanging();
					this._ISPAY = value;
					this.SendPropertyChanged("ISPAY");
					this.OnISPAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP", DbType="Bit NOT NULL")]
		public bool APP
		{
			get
			{
				return this._APP;
			}
			set
			{
				if ((this._APP != value))
				{
					this.OnAPPChanging(value);
					this.SendPropertyChanging();
					this._APP = value;
					this.SendPropertyChanged("APP");
					this.OnAPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_USER", DbType="Int")]
		public System.Nullable<int> KD_USER
		{
			get
			{
				return this._KD_USER;
			}
			set
			{
				if ((this._KD_USER != value))
				{
					this.OnKD_USERChanging(value);
					this.SendPropertyChanging();
					this._KD_USER = value;
					this.SendPropertyChanged("KD_USER");
					this.OnKD_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAG", DbType="VarChar(12)")]
		public string TAG
		{
			get
			{
				return this._TAG;
			}
			set
			{
				if ((this._TAG != value))
				{
					this.OnTAGChanging(value);
					this.SendPropertyChanging();
					this._TAG = value;
					this.SendPropertyChanged("TAG");
					this.OnTAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUNAS", DbType="Bit NOT NULL")]
		public bool LUNAS
		{
			get
			{
				return this._LUNAS;
			}
			set
			{
				if ((this._LUNAS != value))
				{
					this.OnLUNASChanging(value);
					this.SendPropertyChanging();
					this._LUNAS = value;
					this.SendPropertyChanged("LUNAS");
					this.OnLUNASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGL_LUNAS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TGL_LUNAS
		{
			get
			{
				return this._TGL_LUNAS;
			}
			set
			{
				if ((this._TGL_LUNAS != value))
				{
					this.OnTGL_LUNASChanging(value);
					this.SendPropertyChanging();
					this._TGL_LUNAS = value;
					this.SendPropertyChanged("TGL_LUNAS");
					this.OnTGL_LUNASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACC_DR", DbType="Bit NOT NULL")]
		public bool ACC_DR
		{
			get
			{
				return this._ACC_DR;
			}
			set
			{
				if ((this._ACC_DR != value))
				{
					this.OnACC_DRChanging(value);
					this.SendPropertyChanging();
					this._ACC_DR = value;
					this.SendPropertyChanged("ACC_DR");
					this.OnACC_DRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderMng", DbType="VarChar(10)")]
		public string OrderMng
		{
			get
			{
				return this._OrderMng;
			}
			set
			{
				if ((this._OrderMng != value))
				{
					this.OnOrderMngChanging(value);
					this.SendPropertyChanging();
					this._OrderMng = value;
					this.SendPropertyChanged("OrderMng");
					this.OnOrderMngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dilayani", DbType="VarBinary(10)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Dilayani
		{
			get
			{
				return this._Dilayani;
			}
			set
			{
				if ((this._Dilayani != value))
				{
					this.OnDilayaniChanging(value);
					this.SendPropertyChanging();
					this._Dilayani = value;
					this.SendPropertyChanged("Dilayani");
					this.OnDilayaniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verified", DbType="Int")]
		public System.Nullable<int> verified
		{
			get
			{
				return this._verified;
			}
			set
			{
				if ((this._verified != value))
				{
					this.OnverifiedChanging(value);
					this.SendPropertyChanging();
					this._verified = value;
					this.SendPropertyChanged("verified");
					this.OnverifiedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PAYMENT")]
	public partial class PAYMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _KD_PAY;
		
		private byte _JENIS_PAY;
		
		private string _URAIAN;
		
		private System.Nullable<double> _CREDIT_LIMIT;
		
		private string _KD_CUSTOMER;
		
		private System.Nullable<bool> _STATUS_AKTIF;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKD_PAYChanging(string value);
    partial void OnKD_PAYChanged();
    partial void OnJENIS_PAYChanging(byte value);
    partial void OnJENIS_PAYChanged();
    partial void OnURAIANChanging(string value);
    partial void OnURAIANChanged();
    partial void OnCREDIT_LIMITChanging(System.Nullable<double> value);
    partial void OnCREDIT_LIMITChanged();
    partial void OnKD_CUSTOMERChanging(string value);
    partial void OnKD_CUSTOMERChanged();
    partial void OnSTATUS_AKTIFChanging(System.Nullable<bool> value);
    partial void OnSTATUS_AKTIFChanged();
    #endregion
		
		public PAYMENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_PAY", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string KD_PAY
		{
			get
			{
				return this._KD_PAY;
			}
			set
			{
				if ((this._KD_PAY != value))
				{
					this.OnKD_PAYChanging(value);
					this.SendPropertyChanging();
					this._KD_PAY = value;
					this.SendPropertyChanged("KD_PAY");
					this.OnKD_PAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JENIS_PAY", DbType="TinyInt NOT NULL")]
		public byte JENIS_PAY
		{
			get
			{
				return this._JENIS_PAY;
			}
			set
			{
				if ((this._JENIS_PAY != value))
				{
					this.OnJENIS_PAYChanging(value);
					this.SendPropertyChanging();
					this._JENIS_PAY = value;
					this.SendPropertyChanged("JENIS_PAY");
					this.OnJENIS_PAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URAIAN", DbType="VarChar(30)")]
		public string URAIAN
		{
			get
			{
				return this._URAIAN;
			}
			set
			{
				if ((this._URAIAN != value))
				{
					this.OnURAIANChanging(value);
					this.SendPropertyChanging();
					this._URAIAN = value;
					this.SendPropertyChanged("URAIAN");
					this.OnURAIANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREDIT_LIMIT", DbType="Float")]
		public System.Nullable<double> CREDIT_LIMIT
		{
			get
			{
				return this._CREDIT_LIMIT;
			}
			set
			{
				if ((this._CREDIT_LIMIT != value))
				{
					this.OnCREDIT_LIMITChanging(value);
					this.SendPropertyChanging();
					this._CREDIT_LIMIT = value;
					this.SendPropertyChanged("CREDIT_LIMIT");
					this.OnCREDIT_LIMITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KD_CUSTOMER", DbType="VarChar(10)")]
		public string KD_CUSTOMER
		{
			get
			{
				return this._KD_CUSTOMER;
			}
			set
			{
				if ((this._KD_CUSTOMER != value))
				{
					this.OnKD_CUSTOMERChanging(value);
					this.SendPropertyChanging();
					this._KD_CUSTOMER = value;
					this.SendPropertyChanged("KD_CUSTOMER");
					this.OnKD_CUSTOMERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_AKTIF", DbType="Bit")]
		public System.Nullable<bool> STATUS_AKTIF
		{
			get
			{
				return this._STATUS_AKTIF;
			}
			set
			{
				if ((this._STATUS_AKTIF != value))
				{
					this.OnSTATUS_AKTIFChanging(value);
					this.SendPropertyChanging();
					this._STATUS_AKTIF = value;
					this.SendPropertyChanged("STATUS_AKTIF");
					this.OnSTATUS_AKTIFChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
